spring.application.name=Muzan

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/muzan_db
spring.datasource.username=root
spring.datasource.password=root12345

#JPA
spring.jpa.hibernate.ddl-auto=update

price.scrape.interval=3600000
spring.jpa.open-in-view=true