spring.application.name=PricePulse

# Database - H2
spring.datasource.url=jdbc:h2:mem:muzan_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Scraping
price.scrape.interval=3600000

# Email (disabled for demo)
spring.mail.host=localhost
spring.mail.port=25
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Cache (disabled for demo)
spring.cache.type=none

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.enabled=true

# Server
server.port=${PORT:8080}

# H2 data init
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:h2:mem:muzan_db;NON_KEYWORDS=VALUE;DATABASE_TO_UPPER=FALSE