spring.application.name=PricePulse

spring.datasource.url=jdbc:h2:mem:muzan_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

price.scrape.interval=3600000



spring.cache.type=none

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=https://pricepulse-production-ed3b.up.railway.app/api-docs

server.port=${PORT:8080}
server.forward-headers-strategy=framework